/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TheKiller
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
        this.setTitle("Proyecto Interprete Traductor ASCII");
        origen.setLineWrap(true);
        destino.setLineWrap(true);
        origen.setWrapStyleWord(true);
        destino.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        origen = new javax.swing.JTextArea();
        btnBinText = new javax.swing.JButton();
        BtnTextBin = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        destino = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        origen.setColumns(20);
        origen.setRows(5);
        jScrollPane1.setViewportView(origen);

        btnBinText.setText("Binario a Texto");
        btnBinText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBinTextActionPerformed(evt);
            }
        });

        BtnTextBin.setText("Texto a Binario");
        BtnTextBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTextBinActionPerformed(evt);
            }
        });

        destino.setColumns(20);
        destino.setRows(5);
        jScrollPane2.setViewportView(destino);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INGRESE TEXTO O CODIGO BINARIO");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RESULTADO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnTextBin)
                    .addComponent(btnBinText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btnBinText, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(BtnTextBin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(186, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTextBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTextBinActionPerformed
        String texto = origen.getText();

        String codigoBinario = "";//guarda el en binario
        for (int i = 0; i < texto.length(); i++) {//recorre el texto ingresado
            char letra = texto.charAt(i);//separa letra a letra
            /* si el binario de la letra es menor a 8 bit entonces se le agrega
             un cero a la izquierda para llenar el bit restante*/
            int aux = Binario((int) (letra)).length();//almacena largo del binario d ela letra debuelta
            for (int j = 0; j < 8; j++) {//recorrido de 8 characteres
                if (aux < 8) {//si el largo del binario es menor a 7 (0-7)entonces
                    codigoBinario = codigoBinario + "0";//agregar 0 a la concadenacion
                    aux++;//aumentar el largo del binario
                }
            }
            /*se concatena el binario de cada letra separado por un espacio. al metodo binario
             se le pasa por parametro el decimal correspondiente a cada letra*/
            codigoBinario = codigoBinario + Binario((int) (letra)) + " ";
        }
        destino.setText(codigoBinario);/*imprime el codigo binario completo*/
    }//GEN-LAST:event_BtnTextBinActionPerformed

    private void btnBinTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBinTextActionPerformed
        /*almacena el codigo binario sin el primer y ultimo espacio de la frase*/
        String palabra = origen.getText().trim().replaceAll(" ", "");
        destino.setText(separaPorDigito(palabra));
    }//GEN-LAST:event_btnBinTextActionPerformed

    private String separaPorDigito(String digitoBinario) {
        String frase = "";//almacena la frase completa

        for (int i = 0; i < digitoBinario.length(); i += 8) {//recorre la frase de 8 en 8
            /*separa la cadena cada 8 digitos con substring*/
            String cadenaSeparada = digitoBinario.substring(i, i + 8);
            /*entrega un numero decimal a partir de un numero binario de 8 bit*/
            int decimal = Integer.parseInt(cadenaSeparada, 2);
            /*concadena la drase y transfroma el decimal a Ascii*/
            frase = frase + (char) decimal;
        }
        return frase;//retorna la frase completa
    }

    private String Binario(int Decimal) {
        int R, x = 0;//variables que se implementaran
        String Binario = ""; //guarda el contenido en codigo binario
        R = Decimal % 2;//resto del parametro 
        if (R == 1) {//si el resto es 1
            while (Decimal > 1) {//si el parametro es mas grande q el resto
                Decimal /= 2;//entonces decimal se divide en 2 y se guarda en decimal
                x = Decimal % 2;//x contendra el resto del decimal
                Binario = String.valueOf(x + Binario);//binario se ira formando de forma correcta y no alreves
            }
        } else {//si resto no es 1
            while (Decimal > 0) {//y decimal es mayor a 0
                Decimal /= 2;//decimal se divide en 2
                x = Decimal % 2;//x contendra el resto del decimal resultante
                Binario = String.valueOf(x + Binario);//se forma el numero en binario de forma correcta
            }
        }
        return String.valueOf(Binario + x);//devuelve el binario resultante mas el ultimo bit
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTextBin;
    private javax.swing.JButton btnBinText;
    private javax.swing.JTextArea destino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea origen;
    // End of variables declaration//GEN-END:variables
}
